config/routes.rb
Rails.application.routes.draw do
  resources :books
  root 'books#index'
  get 'novels' => 'books#novel'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  # GET /books
  # GET /books.json

  def novel
    @books = Book.all
  end

  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show; end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit; end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:book_title, :author, :genre, :reading_level, :number_of_pages)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.text_field :book_title, id: :book_book_title, class: 'form-control', placeholder:'Title' %>
  </div>

  <div class="form-group">
    <%= form.text_field :author, id: :book_author, class: 'form-control', placeholder:'Author' %>
  </div>

  <div class="form-group">
    <%= form.text_field :genre, id: :book_genre, class: 'form-control', placeholder: 'Genre' %>
  </div>

  <div class="form-group">
    <%= form.number_field :reading_level, id: :book_reading_level, class: 'form-control', placeholder: 'Reading Level (1-10)' %>
  </div>

  <div class="form-group">
    <%= form.number_field :number_of_pages, id: :book_number_of_pages, placeholder: 'Number of Pages', class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary', style: 'margin-bottom: 25px; margin-top: 25px;' %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Book title</th>
      <th>Author</th>
      <th>Genre</th>
      <th>Reading level</th>
      <th>Number of pages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.book_title %></td>
        <td><%= book.author %></td>
        <td><%= book.genre %></td>
        <td><%= book.reading_level %></td>
        <td><%= book.number_of_pages %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/novel.html.erb
<p id="notice"><%= notice %></p>

<h1 style="text-align: center">Novels</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Book title</th>
    <th>Author</th>
    <th>Genre</th>
    <th>Reading level</th>
    <th>Number of pages</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @books.each do |book| %>
    <tr>
      <%if book.genre.downcase.split.include?('novel') && book.number_of_pages > 240 %>
        <td><%= book.book_title %></td>
        <td><%= book.author %></td>
        <td><%= book.genre %></td>
        <td><%= book.reading_level %></td>
        <td><%= book.number_of_pages %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book title:</strong>
  <%= @book.book_title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @book.genre %>
</p>

<p>
  <strong>Reading level:</strong>
  <%= @book.reading_level %>
</p>

<p>
  <strong>Number of pages:</strong>
  <%= @book.number_of_pages %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Library</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <!-- A grey horizontal navbar that becomes vertical on small screens -->
  <nav class="navbar navbar-expand-sm bg-light">

    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'All Books', '/'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Long Novels', novels_path %>
      </li>
    </ul>

  </nav>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>